/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `Posts`;

CREATE TABLE `Posts` (
  `id` varchar(250) NOT NULL DEFAULT '',
  `message` longtext,
  `created_at` varchar(250) DEFAULT NULL,
  `updated_at` varchar(250) DEFAULT NULL,
  `pin_count` int(11) DEFAULT NULL,
  `color` varchar(250) DEFAULT NULL,
  `thanks_count` int(11) DEFAULT NULL,
  `child_count` int(11) DEFAULT NULL,
  `replier` int(11) DEFAULT NULL,
  `discovered_by` int(11) DEFAULT NULL,
  `vote_count` int(11) DEFAULT NULL,
  `share_count` int(11) DEFAULT NULL,
  `user_handle` varchar(250) DEFAULT NULL,
  `post_own` varchar(250) DEFAULT NULL,
  `distance` int(11) DEFAULT NULL,
  `image_url` varchar(250) DEFAULT NULL,
  `location` varchar(250) DEFAULT NULL,
  `from_home` varchar(250) DEFAULT NULL,
  `parent_id` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
